name: PullRequest Auto Merge
on:
  pull_request:

jobs:
  build:
    name: Merge
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
    steps:
    - name: setup git
      shell: bash
      run: |
        git config --global user.email "actions@github.com"
        git config --global user.name "actions"
        git fetch origin ${{ github.base_ref }}
        git merge ${{ github.base_ref }}
        git push origin page