name: PullRequest Auto Merge
on:
  pull_request:

jobs:
  build:
    name: Merge
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
    steps:
    
    - uses: actions/checkout@v2
      with:
        submodules: true

    - name: setup git
      shell: bash
      run: |
        git config --global user.email "actions@github.com"
        git config --global user.name "actions"
        git branch
        git checkout -b ${{ github.event.pull_request.head.ref }} origin/${{ github.event.pull_request.head.ref }}
        git pull
        git checkout main
        git pull
        git merge ${{ github.event.pull_request.head.ref }}
        git push