name: UnityTest

on: 
  push:
  workflow_dispatch: 

jobs:
  build-unity:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@v2
      # Execute scripts: RuntimeUnitTestToolkit(Linux64/Mono2x)
      # /opt/Unity/Editor/Unity -quit -batchmode -nographics -silent-crashes -logFile -projectPath . -executeMethod UnitTestBuilder.BuildUnitTest /headless /ScriptBackend Mono2x /BuildTarget StandaloneLinux64
      - name: Build UnitTest(Linux64, mono)
        uses: game-ci/unity-builder@v2.0-alpha-6
        env:
          UNITY_LICENSE: ${{ secrets[UNITY_LICENSE_2020] }}
        with:
          projectPath: RuntimeUnitTestToolkit
          unityVersion: 2020.1.5f1
          targetPlatform: StandaloneLinux64
          buildMethod: UnitTestBuilder.BuildUnitTest
          customParameters: /headless /ScriptBackend Mono2x
          versioning: None
      - name: Execute UnitTest
        run: ./RuntimeUnitTestToolkit/bin/UnitTest/StandaloneLinux64_Mono2x/test

